# Generated by Django 4.2.7 on 2023-11-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='модель продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_type', models.CharField(choices=[('FC', 'Завод'), ('RN', 'Розничная сеть'), ('IE', 'Индивидуальный предприниматель')], max_length=2, verbose_name='тип звена')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='уровень звена')),
                ('title', models.CharField(max_length=150, verbose_name='название компании')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='страна')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('street', models.CharField(max_length=150, verbose_name='улица')),
                ('house', models.PositiveIntegerField(verbose_name='номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='задолженность')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='products', to='network.product', verbose_name='продукты')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.company', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
